# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41b8a3c658381d26dff40a2de1694d964503937ed7b511a60ac72856f93a848f390f4faba8661ce38e2bddde5671cd30bf4bf36372af8693181aaef32dff9033

test:
  secret_key_base: 2cb37f1fe3dc459f27845e9c0c7c3a1f25cfbbe3c1b9dc7a722c037c1f5f59593f9fcb89a4d047cb0dae19b728410c79905e5b27852c9e9f32cf40edd1f2e0af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
